refactor: update social card design
open-sauced/opengraph pull request #52
Opened 2023-06-09 14:19 UTC by OgDev-01

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Description
This PR updates the social card design 

## Related Tickets & Documents
closes #44 

## Mobile & Desktop Screenshots/Recordings
### Insights Page 
<img width="1195" alt="image" src="https://github.com/open-sauced/opengraph.opensauced.pizza/assets/62995161/14a43103-9969-4b51-a2a4-54eb1402adf1">
<img width="1199" alt="image" src="https://github.com/open-sauced/opengraph.opensauced.pizza/assets/62995161/1f08f71a-2946-4caa-ae97-99be83e82477">

### Users
<img width="1197" alt="image" src="https://github.com/open-sauced/opengraph.opensauced.pizza/assets/62995161/54836280-20c7-47f2-ad25-f8f9ddb45759">
<img width="1199" alt="image" src="https://github.com/open-sauced/opengraph.opensauced.pizza/assets/62995161/b368e8c5-0e55-4cb9-a7a0-375be899eb31">

### Highlights
<img width="1199" alt="image" src="https://github.com/open-sauced/opengraph.opensauced.pizza/assets/62995161/702afd33-06be-4d7c-8ae8-609f5d5a12a0">
<img width="1198" alt="image" src="https://github.com/open-sauced/opengraph.opensauced.pizza/assets/62995161/c860806c-4a14-4102-b21e-96acb70d7a6f">

## Added tests?

- [x] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

## [optional] What gif best describes this PR or how it makes you feel?

<img src="https://media2.giphy.com/media/5vYtqExBsy8nwoNo53/giphy.gif"/>

2023-06-09 14:26 UTC, brandonroberts commented on src/social-card/templates/insight-card.template.ts
> +        <p tw="font-medium text-48px tracking-tight"> ${pageName}: Insights </p>
I don't think we need `: Insights` here if its in the header above

```suggestion
        <p tw="font-medium text-48px tracking-tight"> ${pageName} </p>
```

2023-06-09 17:51 UTC, bdougie commented
I'm thinking we might want to add the copy or previews text

2023-06-09 20:06 UTC, isabensusan commented
I think it'd look better if we used bold titles instead of semi-bold, and grey for the subtitles (see screenshot), just to ensure a clear content hierarchy, but honestly it's a small detail and it still looks good the way it is right now.

<img width="792" alt="image" src="https://github.com/open-sauced/opengraph.opensauced.pizza/assets/27322879/bf9b1ddb-723f-4f57-92dd-9b76643047b1">

2023-06-14 00:06 UTC, bdougie requested changes
I know it didn't make the design, but can we add the highlight copy back to the card (in grey). This was pretty useful and as long as we truncate the characters shown to 300, it should work.

2023-06-20 19:34 UTC, OgDev-01 commented
a quick question @bdougie, are we replacing the username with the highlights copy or adding the copy below the username on the highlights card?

2023-06-20 19:39 UTC, bdougie commented
> a quick question @bdougie, are we replacing the username with the highlights copy or adding the copy below the username on the highlights card?

Replace the user name.

2023-06-20 22:34 UTC, OgDev-01 commented
Updated copy 
<img width="1195" alt="image" src="https://github.com/open-sauced/opengraph/assets/62995161/3b2ad302-b39e-47a8-bb3e-2f7e8804ca90">

cc: @bdougie @brandonroberts

2023-06-20 22:35 UTC, bdougie approved these changes

2023-06-20 23:52 UTC, jpmcb approved these changes
Very nice!! 👏🏼 🔥 
![jpmcb](https://github.com/open-sauced/opengraph/assets/23109390/83b1c86b-8889-4258-bcb0-55d6b06d9a76)

I wonder what's going on with the bottom right of my card. Almost looks like the small green gets cut off early before it curves back up?

2023-06-21 14:59 UTC, brandonroberts approved these changes

2023-06-22 17:01 UTC, merged